services:
  client:
    build: ./client
    command: sh -c "npm install && npm run dev"
    restart: unless-stopped
    ports:
      - 4200:4200
    volumes:
      - ./client:/client
    environment:
      - WDS_SOCKET=127.0.0.1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true

  server:
    build: ./server
    restart: unless-stopped
    ports:
      - 3200:3200
    volumes:
      - ./server:/server
    environment:
      - DBNAME=${DBNAME}
      - DBUSERNAME=${DBUSERNAME}
      - DBPASS=${DBPASS}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - NODE_ENV=${NODE_ENV}
      - FRONTEND_URL=${FRONTEND_URL}
      - JWTSECRETKEY=${JWTSECRETKEY}

  db:
    image: postgres:16
    restart: unless-stopped
    shm_size: 128mb
    volumes:
      - ./db_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5433:5432
    container_name: pawplanner-db-1
    environment:
      - POSTGRES_PASSWORD=${DBPASS}

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
