services:
  client:
    image: dolpheus89/prod_client_pawplanner
    command: sh -c "npm ci && npm run build && npm run preview"
    restart: unless-stopped
    ports:
      - 4201:4200
    volumes:
      - web-client-build:/client/dist
    environment:
      - WDS_SOCKET=127.0.0.1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - VITE_NODE_ENV="production"

  server:
    image: dolpheus89/prod_server_pawplanner
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 3201:3200
    environment:
      - DBNAME=${DBNAME}
      - DBUSERNAME=${DBUSERNAME}
      - DBPASS=${DBPASS}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - NODE_ENV="production"
      - FRONTEND_URL=${FRONTEND_URL}
      - JWTSECRETKEY=${JWTSECRETKEY}

  db:
    image: postgres:16
    restart: unless-stopped
    shm_size: 128mb
    volumes:
      - ./db_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5434:5432
    container_name: pawplanner-db-1
    environment:
      - POSTGRES_USER=${DBUSERNAME}
      - POSTGRES_PASSWORD=${DBPASS}
      - POSTGRES_DB=${DBNAME}
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8081:8080

  nginx:
    image: nginx:1.21.3
    depends_on:
      - server
      - client
    restart: always
    ports:
      - ${GATEWAY_PORT:-8060}:82
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - web-client-build:/web-client-build
      - ./logs:/var/log/nginx

volumes:
  web-client-build:
  db_data:
