services:
  client:
    build: ./client
    command: sh -c "npm install && npm run dev"
    restart: unless-stopped
    ports:
      - 4200:4200
    volumes:
      - ./client:/client
    volumes_from:
      - shared
    depends_on:
      - shared
    environment:
      - WDS_SOCKET=127.0.0.1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    env_file:
      - .env

  server:
    build: ./server
    restart: unless-stopped
    ports:
      - 3200:3200
    volumes:
      - ./server:/server
    command: sh -c "ln -sf /shared && npm run start"
    volumes_from:
      - shared
    depends_on:
      - shared
      - db
    env_file:
      - .env

  shared:
    build: ./shared
    volumes:
      - ./shared:/shared

  db:
    image: postgres:16
    restart: unless-stopped
    shm_size: 128mb
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    container_name: pawplanner-db-1
    environment:
      - POSTGRES_USER=${DBUSERNAME}
      - POSTGRES_PASSWORD=${DBPASS}
      - POSTGRES_DB=${DBNAME}

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080