name: Run client tests

on:
  push:
    branches:
          - "*"
  pull_request:
    branches:
      - main
      - staging
      - develop
  workflow_dispatch:

jobs:
  client:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js (client)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install client dependencies
        working-directory: ./client
        run: |
          npm install

      - name: Run client tests
        working-directory: ./client
        run: |
          npm test