name: Compile and push server image


on:


  push:
    branches: ["main"]


  workflow_dispatch:


jobs:

  build:


    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4


      # login with Docker

      - uses: docker/login-action@v3
        name: Login to Docker Hub

        with:

          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      

      # prepare buildx for docker

      - uses: docker/setup-buildx-action@v3
        name: Set up Docker Buildx


      # build and push the newly created image

      - uses: docker/build-push-action@v5
        name: Build and push

        with:

          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/prod_server_pawplanner:latest