name: Run server tests

on:
  pull_request:
    branches:
      - main
      - staging
      - develop
  workflow_dispatch:

jobs:
  server:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js (server)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install server dependencies
        working-directory: ./server
        run: |
          npm install

      - name: Run server tests
        working-directory: ./server
        run: |
          npm test
