name: Compile and push client image


on:
  push:
    branches: ["staging"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:


  build:


    runs-on: ubuntu-latest


    steps:

      - uses: actions/checkout@v2

      # login with Docker

      - uses: docker/login-action@v1
        name: Login to Docker Hub

        with:

          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      

      # prepare buildx for docker

      - uses: docker/setup-buildx-action@v1
        name: Set up Docker Buildx


      # build and push the newly created image

      - uses: docker/build-push-action@v2
        name: Build and push

        with:

          context: ./client
          file: ./client/Dockerfile
          push: true

          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/staging_client_pawplanner:latest